// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users.proto

/*
	Package users is a generated protocol buffer package.

	It is generated from these files:
		users.proto

	It has these top-level messages:
		UserUUID
		UpsertUserOpts
		AuthUserByEmailAndPasswordOpts
		AuthUserByEmailAndPasswordPayload
		UserPayload
		UsersResponse
*/
package users

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/canary-health/protobuf/types"
import _ "github.com/canary-health/protobuf/types"
import _ "github.com/canary-health/protobuf/types"

import time "time"

import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UserUUID struct {
	UserUUID string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty" db:"user_uuid"`
}

func (m *UserUUID) Reset()                    { *m = UserUUID{} }
func (m *UserUUID) String() string            { return proto.CompactTextString(m) }
func (*UserUUID) ProtoMessage()               {}
func (*UserUUID) Descriptor() ([]byte, []int) { return fileDescriptorUsers, []int{0} }

func (m *UserUUID) GetUserUUID() string {
	if m != nil {
		return m.UserUUID
	}
	return ""
}

type UpsertUserOpts struct {
	UserUUID       string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty" db:"user_uuid"`
	ServiceSlug    string `protobuf:"bytes,2,opt,name=service_slug,json=serviceSlug,proto3" json:"service_slug,omitempty" db:"service_slug"`
	Email          string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password       string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	VerifyPassword string `protobuf:"bytes,5,opt,name=verify_password,json=verifyPassword,proto3" json:"verify_password,omitempty"`
}

func (m *UpsertUserOpts) Reset()                    { *m = UpsertUserOpts{} }
func (m *UpsertUserOpts) String() string            { return proto.CompactTextString(m) }
func (*UpsertUserOpts) ProtoMessage()               {}
func (*UpsertUserOpts) Descriptor() ([]byte, []int) { return fileDescriptorUsers, []int{1} }

func (m *UpsertUserOpts) GetUserUUID() string {
	if m != nil {
		return m.UserUUID
	}
	return ""
}

func (m *UpsertUserOpts) GetServiceSlug() string {
	if m != nil {
		return m.ServiceSlug
	}
	return ""
}

func (m *UpsertUserOpts) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpsertUserOpts) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpsertUserOpts) GetVerifyPassword() string {
	if m != nil {
		return m.VerifyPassword
	}
	return ""
}

type AuthUserByEmailAndPasswordOpts struct {
	ServiceSlug string `protobuf:"bytes,1,opt,name=service_slug,json=serviceSlug,proto3" json:"service_slug,omitempty" db:"service_slug"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password    string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *AuthUserByEmailAndPasswordOpts) Reset()         { *m = AuthUserByEmailAndPasswordOpts{} }
func (m *AuthUserByEmailAndPasswordOpts) String() string { return proto.CompactTextString(m) }
func (*AuthUserByEmailAndPasswordOpts) ProtoMessage()    {}
func (*AuthUserByEmailAndPasswordOpts) Descriptor() ([]byte, []int) {
	return fileDescriptorUsers, []int{2}
}

func (m *AuthUserByEmailAndPasswordOpts) GetServiceSlug() string {
	if m != nil {
		return m.ServiceSlug
	}
	return ""
}

func (m *AuthUserByEmailAndPasswordOpts) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthUserByEmailAndPasswordOpts) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthUserByEmailAndPasswordPayload struct {
	UserUUID    string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty" db:"user_uuid"`
	ServiceSlug string `protobuf:"bytes,2,opt,name=service_slug,json=serviceSlug,proto3" json:"service_slug,omitempty" db:"service_slug"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password    string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *AuthUserByEmailAndPasswordPayload) Reset()         { *m = AuthUserByEmailAndPasswordPayload{} }
func (m *AuthUserByEmailAndPasswordPayload) String() string { return proto.CompactTextString(m) }
func (*AuthUserByEmailAndPasswordPayload) ProtoMessage()    {}
func (*AuthUserByEmailAndPasswordPayload) Descriptor() ([]byte, []int) {
	return fileDescriptorUsers, []int{3}
}

func (m *AuthUserByEmailAndPasswordPayload) GetUserUUID() string {
	if m != nil {
		return m.UserUUID
	}
	return ""
}

func (m *AuthUserByEmailAndPasswordPayload) GetServiceSlug() string {
	if m != nil {
		return m.ServiceSlug
	}
	return ""
}

func (m *AuthUserByEmailAndPasswordPayload) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthUserByEmailAndPasswordPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// UserPayload should never include password
type UserPayload struct {
	UserUUID    string     `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty" db:"user_uuid"`
	ServiceSlug string     `protobuf:"bytes,2,opt,name=service_slug,json=serviceSlug,proto3" json:"service_slug,omitempty" db:"service_slug"`
	Email       string     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt   *time.Time `protobuf:"bytes,996,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   *time.Time `protobuf:"bytes,997,opt,name=updated_at,json=updatedAt,stdtime" json:"updated_at,omitempty" db:"updated_at"`
	ArchivedAt  *time.Time `protobuf:"bytes,998,opt,name=archived_at,json=archivedAt,stdtime" json:"archived_at,omitempty" db:"archived_at"`
	DeletedAt   *time.Time `protobuf:"bytes,999,opt,name=deleted_at,json=deletedAt,stdtime" json:"deleted_at,omitempty" db:"deleted_at"`
}

func (m *UserPayload) Reset()                    { *m = UserPayload{} }
func (m *UserPayload) String() string            { return proto.CompactTextString(m) }
func (*UserPayload) ProtoMessage()               {}
func (*UserPayload) Descriptor() ([]byte, []int) { return fileDescriptorUsers, []int{4} }

func (m *UserPayload) GetUserUUID() string {
	if m != nil {
		return m.UserUUID
	}
	return ""
}

func (m *UserPayload) GetServiceSlug() string {
	if m != nil {
		return m.ServiceSlug
	}
	return ""
}

func (m *UserPayload) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserPayload) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserPayload) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *UserPayload) GetArchivedAt() *time.Time {
	if m != nil {
		return m.ArchivedAt
	}
	return nil
}

func (m *UserPayload) GetDeletedAt() *time.Time {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type UsersResponse struct {
	Data []*UserPayload `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *UsersResponse) Reset()                    { *m = UsersResponse{} }
func (m *UsersResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()               {}
func (*UsersResponse) Descriptor() ([]byte, []int) { return fileDescriptorUsers, []int{5} }

func (m *UsersResponse) GetData() []*UserPayload {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserUUID)(nil), "canaryhealth.idp.users.UserUUID")
	proto.RegisterType((*UpsertUserOpts)(nil), "canaryhealth.idp.users.UpsertUserOpts")
	proto.RegisterType((*AuthUserByEmailAndPasswordOpts)(nil), "canaryhealth.idp.users.AuthUserByEmailAndPasswordOpts")
	proto.RegisterType((*AuthUserByEmailAndPasswordPayload)(nil), "canaryhealth.idp.users.AuthUserByEmailAndPasswordPayload")
	proto.RegisterType((*UserPayload)(nil), "canaryhealth.idp.users.UserPayload")
	proto.RegisterType((*UsersResponse)(nil), "canaryhealth.idp.users.UsersResponse")
}
func (m *UserUUID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserUUID) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserUUID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.UserUUID)))
		i += copy(dAtA[i:], m.UserUUID)
	}
	return i, nil
}

func (m *UpsertUserOpts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpsertUserOpts) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserUUID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.UserUUID)))
		i += copy(dAtA[i:], m.UserUUID)
	}
	if len(m.ServiceSlug) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.ServiceSlug)))
		i += copy(dAtA[i:], m.ServiceSlug)
	}
	if len(m.Email) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.Email)))
		i += copy(dAtA[i:], m.Email)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	if len(m.VerifyPassword) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.VerifyPassword)))
		i += copy(dAtA[i:], m.VerifyPassword)
	}
	return i, nil
}

func (m *AuthUserByEmailAndPasswordOpts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthUserByEmailAndPasswordOpts) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ServiceSlug) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.ServiceSlug)))
		i += copy(dAtA[i:], m.ServiceSlug)
	}
	if len(m.Email) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.Email)))
		i += copy(dAtA[i:], m.Email)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	return i, nil
}

func (m *AuthUserByEmailAndPasswordPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthUserByEmailAndPasswordPayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserUUID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.UserUUID)))
		i += copy(dAtA[i:], m.UserUUID)
	}
	if len(m.ServiceSlug) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.ServiceSlug)))
		i += copy(dAtA[i:], m.ServiceSlug)
	}
	if len(m.Email) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.Email)))
		i += copy(dAtA[i:], m.Email)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	return i, nil
}

func (m *UserPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserPayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserUUID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.UserUUID)))
		i += copy(dAtA[i:], m.UserUUID)
	}
	if len(m.ServiceSlug) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.ServiceSlug)))
		i += copy(dAtA[i:], m.ServiceSlug)
	}
	if len(m.Email) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintUsers(dAtA, i, uint64(len(m.Email)))
		i += copy(dAtA[i:], m.Email)
	}
	if m.CreatedAt != nil {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintUsers(dAtA, i, uint64(types.SizeOfStdTime(*m.CreatedAt)))
		n1, err := types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.UpdatedAt != nil {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintUsers(dAtA, i, uint64(types.SizeOfStdTime(*m.UpdatedAt)))
		n2, err := types.StdTimeMarshalTo(*m.UpdatedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.ArchivedAt != nil {
		dAtA[i] = 0xb2
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintUsers(dAtA, i, uint64(types.SizeOfStdTime(*m.ArchivedAt)))
		n3, err := types.StdTimeMarshalTo(*m.ArchivedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.DeletedAt != nil {
		dAtA[i] = 0xba
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintUsers(dAtA, i, uint64(types.SizeOfStdTime(*m.DeletedAt)))
		n4, err := types.StdTimeMarshalTo(*m.DeletedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func (m *UsersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UsersResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		for _, msg := range m.Data {
			dAtA[i] = 0xa
			i++
			i = encodeVarintUsers(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeVarintUsers(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *UserUUID) Size() (n int) {
	var l int
	_ = l
	l = len(m.UserUUID)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	return n
}

func (m *UpsertUserOpts) Size() (n int) {
	var l int
	_ = l
	l = len(m.UserUUID)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.ServiceSlug)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.VerifyPassword)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	return n
}

func (m *AuthUserByEmailAndPasswordOpts) Size() (n int) {
	var l int
	_ = l
	l = len(m.ServiceSlug)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	return n
}

func (m *AuthUserByEmailAndPasswordPayload) Size() (n int) {
	var l int
	_ = l
	l = len(m.UserUUID)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.ServiceSlug)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	return n
}

func (m *UserPayload) Size() (n int) {
	var l int
	_ = l
	l = len(m.UserUUID)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.ServiceSlug)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovUsers(uint64(l))
	}
	if m.CreatedAt != nil {
		l = types.SizeOfStdTime(*m.CreatedAt)
		n += 2 + l + sovUsers(uint64(l))
	}
	if m.UpdatedAt != nil {
		l = types.SizeOfStdTime(*m.UpdatedAt)
		n += 2 + l + sovUsers(uint64(l))
	}
	if m.ArchivedAt != nil {
		l = types.SizeOfStdTime(*m.ArchivedAt)
		n += 2 + l + sovUsers(uint64(l))
	}
	if m.DeletedAt != nil {
		l = types.SizeOfStdTime(*m.DeletedAt)
		n += 2 + l + sovUsers(uint64(l))
	}
	return n
}

func (m *UsersResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.Data) > 0 {
		for _, e := range m.Data {
			l = e.Size()
			n += 1 + l + sovUsers(uint64(l))
		}
	}
	return n
}

func sovUsers(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozUsers(x uint64) (n int) {
	return sovUsers(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserUUID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserUUID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserUUID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthUsers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpsertUserOpts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpsertUserOpts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpsertUserOpts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceSlug", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceSlug = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifyPassword", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerifyPassword = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthUsers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthUserByEmailAndPasswordOpts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthUserByEmailAndPasswordOpts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthUserByEmailAndPasswordOpts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceSlug", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceSlug = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthUsers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthUserByEmailAndPasswordPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthUserByEmailAndPasswordPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthUserByEmailAndPasswordPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceSlug", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceSlug = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthUsers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceSlug", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceSlug = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 996:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 997:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 998:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArchivedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ArchivedAt == nil {
				m.ArchivedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.ArchivedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 999:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAt == nil {
				m.DeletedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.DeletedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthUsers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UsersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsers
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UsersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UsersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsers
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, &UserPayload{})
			if err := m.Data[len(m.Data)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsers(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthUsers
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUsers(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUsers
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUsers
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthUsers
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowUsers
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipUsers(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthUsers = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUsers   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("users.proto", fileDescriptorUsers) }

var fileDescriptorUsers = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xbd, 0x6f, 0xd3, 0x40,
	0x14, 0xe7, 0x9a, 0x06, 0x9a, 0x67, 0x48, 0xe1, 0x04, 0xd4, 0xf2, 0x60, 0x07, 0x23, 0x41, 0x96,
	0x3a, 0x52, 0x90, 0x0a, 0x2a, 0x53, 0x22, 0x10, 0x30, 0x51, 0xb9, 0xa4, 0x03, 0x4b, 0x74, 0x89,
	0xaf, 0x8e, 0x25, 0x27, 0xb6, 0xee, 0xce, 0x41, 0xf9, 0x1f, 0x18, 0xfa, 0x67, 0x31, 0x30, 0xb0,
	0xb1, 0x05, 0x14, 0xbe, 0x66, 0xf2, 0x17, 0xa0, 0x3b, 0x5f, 0x3e, 0x8a, 0x48, 0xdb, 0x88, 0x05,
	0xb6, 0x7b, 0xef, 0xfd, 0xbe, 0xfc, 0x71, 0x0f, 0x8c, 0x8c, 0x53, 0xc6, 0xbd, 0x94, 0x25, 0x22,
	0xc1, 0xb7, 0xbb, 0x64, 0x40, 0xd8, 0xa8, 0x47, 0x49, 0x2c, 0x7a, 0x5e, 0x14, 0xa4, 0x9e, 0x9a,
	0x5a, 0xbb, 0x61, 0x24, 0x7a, 0x59, 0xc7, 0xeb, 0x26, 0xfd, 0x5a, 0x98, 0x84, 0x49, 0x4d, 0xc1,
	0x3b, 0xd9, 0xb1, 0xaa, 0x54, 0xa1, 0x4e, 0xb9, 0x8c, 0xe5, 0x84, 0x49, 0x12, 0xc6, 0x74, 0x81,
	0x12, 0x51, 0x9f, 0x72, 0x41, 0xfa, 0xa9, 0x06, 0xec, 0x2f, 0xe9, 0xe5, 0x96, 0xbb, 0xb9, 0xe7,
	0x12, 0x65, 0x94, 0x52, 0x5e, 0x23, 0xe2, 0xd5, 0x8c, 0xaa, 0x33, 0x5a, 0xf5, 0x8b, 0x72, 0xb3,
	0x2c, 0x0a, 0x34, 0x67, 0xef, 0xa2, 0x9c, 0x38, 0xe2, 0xe2, 0x65, 0x2a, 0xb4, 0x97, 0xfb, 0x0c,
	0xb6, 0x5a, 0x9c, 0xb2, 0x56, 0xeb, 0xc5, 0x13, 0xfc, 0x18, 0x4a, 0xf2, 0x65, 0xb4, 0xa5, 0xac,
	0x89, 0x2a, 0xa8, 0x5a, 0x6a, 0xda, 0x93, 0xb1, 0x33, 0x07, 0x4c, 0xc7, 0x4e, 0x39, 0xe8, 0xec,
	0xbb, 0x73, 0x90, 0xeb, 0x6f, 0xc9, 0x73, 0x4b, 0x1e, 0x27, 0x08, 0xca, 0xad, 0x94, 0x53, 0x26,
	0x24, 0x5c, 0x3a, 0xfc, 0x95, 0x1e, 0x7e, 0x04, 0x57, 0x39, 0x65, 0xc3, 0xa8, 0x4b, 0xdb, 0x3c,
	0xce, 0x42, 0x73, 0x43, 0xf1, 0x6f, 0x4d, 0xc7, 0xce, 0x0d, 0xc9, 0x59, 0x9e, 0xb9, 0xbe, 0xa1,
	0xcb, 0xc3, 0x38, 0x0b, 0xf1, 0x4d, 0x28, 0xd2, 0x3e, 0x89, 0x62, 0xb3, 0x20, 0x29, 0x7e, 0x5e,
	0x60, 0x0b, 0xb6, 0x52, 0xc2, 0xf9, 0x9b, 0x84, 0x05, 0xe6, 0xa6, 0x1a, 0xcc, 0x6b, 0x7c, 0x1f,
	0xb6, 0x87, 0x94, 0x45, 0xc7, 0xa3, 0xf6, 0x1c, 0x52, 0x54, 0x90, 0x72, 0xde, 0x3e, 0xd0, 0x5d,
	0xf7, 0x2d, 0x02, 0xbb, 0x91, 0x89, 0x9e, 0x7c, 0x82, 0xe6, 0xe8, 0xa9, 0x14, 0x6e, 0x0c, 0x82,
	0xd9, 0x58, 0x3d, 0xf4, 0xef, 0xb9, 0xd1, 0xfa, 0xb9, 0x37, 0x56, 0xe5, 0x2e, 0x9c, 0xce, 0xed,
	0xbe, 0x47, 0x70, 0x67, 0x75, 0x9c, 0x03, 0x32, 0x8a, 0x13, 0x12, 0xfc, 0x37, 0x9f, 0xc1, 0xfd,
	0x59, 0x00, 0x43, 0x86, 0xfa, 0x27, 0x83, 0x1f, 0x02, 0x74, 0x19, 0x25, 0x82, 0x06, 0x6d, 0x22,
	0xcc, 0xaf, 0x57, 0x2a, 0xa8, 0x6a, 0xd4, 0x2d, 0x2f, 0xdf, 0x03, 0xde, 0xec, 0x92, 0x79, 0xf3,
	0xcb, 0xdc, 0xdc, 0x99, 0x8e, 0x9d, 0x6d, 0x69, 0xb5, 0xa0, 0xb9, 0x27, 0x9f, 0x1c, 0xe4, 0x97,
	0x74, 0xa3, 0x21, 0xa4, 0x68, 0x96, 0x06, 0x33, 0xd1, 0x6f, 0x6b, 0x88, 0x2e, 0x68, 0x5a, 0x54,
	0x37, 0x1a, 0x02, 0x1f, 0x81, 0x41, 0x58, 0xb7, 0x17, 0x0d, 0x73, 0xd5, 0xef, 0xe7, 0xab, 0x9a,
	0xd3, 0xb1, 0x73, 0x5d, 0xaa, 0x2e, 0xf1, 0x72, 0x59, 0x98, 0x75, 0xf2, 0xb0, 0x01, 0x8d, 0xa9,
	0x0e, 0xfb, 0x63, 0x8d, 0xb0, 0x0b, 0x9a, 0x0e, 0xab, 0x1b, 0x0d, 0xe1, 0x3e, 0x87, 0x6b, 0xf2,
	0x73, 0x72, 0x9f, 0xf2, 0x34, 0x19, 0x70, 0x8a, 0x1f, 0xc2, 0x66, 0x40, 0x04, 0x31, 0x51, 0xa5,
	0x50, 0x35, 0xea, 0x77, 0xbd, 0x3f, 0xef, 0x6b, 0x6f, 0xe9, 0x3f, 0xf1, 0x15, 0xa1, 0xfe, 0x11,
	0x41, 0x51, 0x49, 0xe1, 0x23, 0x80, 0xc5, 0x26, 0xc2, 0xf7, 0x56, 0x4a, 0x9c, 0xda, 0x56, 0x56,
	0xe5, 0x2c, 0x2b, 0xb5, 0x1f, 0x87, 0x60, 0xad, 0xbe, 0x6d, 0x78, 0x6f, 0x15, 0xff, 0xec, 0x85,
	0x71, 0xbe, 0x6f, 0x73, 0xe7, 0xdd, 0xc4, 0x46, 0x1f, 0x26, 0x36, 0xfa, 0x3c, 0xb1, 0xd1, 0xc9,
	0x17, 0xfb, 0xd2, 0xeb, 0xa2, 0x42, 0x74, 0x2e, 0xab, 0x97, 0xfe, 0xe0, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xbb, 0xf6, 0xb9, 0xed, 0xe2, 0x06, 0x00, 0x00,
}
