apiVersion: v1
kind: Service
metadata:
  name: idp-server
  namespace: acceptance
  labels:
    name: idp-server
    part-of: idp
    tier: server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: https
  selector:
    name: idp-server
    part-of: idp
    tier: server
