// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: profiles.proto

/*
	Package profiles is a generated protocol buffer package.

	It is generated from these files:
		profiles.proto

	It has these top-level messages:
		UpsertProfileOpts
		ProfilePayload
*/
package profiles

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/canary-health/idp/_rpc/users"
import _ "github.com/canary-health/protobuf/types"
import _ "github.com/canary-health/protobuf/types"
import _ "github.com/canary-health/protobuf/types"

import time "time"

import types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type UpsertProfileOpts struct {
	UserUUID    string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty" db:"user_uuid"`
	ScreenName  string `protobuf:"bytes,2,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty" db:"screen_name"`
	Avatar      string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Timezone    string `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Locale      string `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
}

func (m *UpsertProfileOpts) Reset()                    { *m = UpsertProfileOpts{} }
func (m *UpsertProfileOpts) String() string            { return proto.CompactTextString(m) }
func (*UpsertProfileOpts) ProtoMessage()               {}
func (*UpsertProfileOpts) Descriptor() ([]byte, []int) { return fileDescriptorProfiles, []int{0} }

func (m *UpsertProfileOpts) GetUserUUID() string {
	if m != nil {
		return m.UserUUID
	}
	return ""
}

func (m *UpsertProfileOpts) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *UpsertProfileOpts) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UpsertProfileOpts) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpsertProfileOpts) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *UpsertProfileOpts) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type ProfilePayload struct {
	UserUUID    string     `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty" db:"user_uuid"`
	ScreenName  string     `protobuf:"bytes,2,opt,name=screen_name,json=screenName,proto3" json:"screen_name,omitempty" db:"screen_name"`
	Avatar      string     `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Timezone    string     `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Locale      string     `protobuf:"bytes,6,opt,name=locale,proto3" json:"locale,omitempty"`
	CreatedAt   *time.Time `protobuf:"bytes,996,opt,name=created_at,json=createdAt,stdtime" json:"created_at,omitempty" db:"created_at"`
	UpdatedAt   *time.Time `protobuf:"bytes,997,opt,name=updated_at,json=updatedAt,stdtime" json:"updated_at,omitempty" db:"updated_at"`
	ArchivedAt  *time.Time `protobuf:"bytes,998,opt,name=archived_at,json=archivedAt,stdtime" json:"archived_at,omitempty" db:"archived_at"`
	DeletedAt   *time.Time `protobuf:"bytes,999,opt,name=deleted_at,json=deletedAt,stdtime" json:"deleted_at,omitempty" db:"deleted_at"`
}

func (m *ProfilePayload) Reset()                    { *m = ProfilePayload{} }
func (m *ProfilePayload) String() string            { return proto.CompactTextString(m) }
func (*ProfilePayload) ProtoMessage()               {}
func (*ProfilePayload) Descriptor() ([]byte, []int) { return fileDescriptorProfiles, []int{1} }

func (m *ProfilePayload) GetUserUUID() string {
	if m != nil {
		return m.UserUUID
	}
	return ""
}

func (m *ProfilePayload) GetScreenName() string {
	if m != nil {
		return m.ScreenName
	}
	return ""
}

func (m *ProfilePayload) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ProfilePayload) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProfilePayload) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *ProfilePayload) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *ProfilePayload) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ProfilePayload) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *ProfilePayload) GetArchivedAt() *time.Time {
	if m != nil {
		return m.ArchivedAt
	}
	return nil
}

func (m *ProfilePayload) GetDeletedAt() *time.Time {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*UpsertProfileOpts)(nil), "canaryhealth.idp.profiles.UpsertProfileOpts")
	proto.RegisterType((*ProfilePayload)(nil), "canaryhealth.idp.profiles.ProfilePayload")
}
func (m *UpsertProfileOpts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpsertProfileOpts) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserUUID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.UserUUID)))
		i += copy(dAtA[i:], m.UserUUID)
	}
	if len(m.ScreenName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.ScreenName)))
		i += copy(dAtA[i:], m.ScreenName)
	}
	if len(m.Avatar) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Avatar)))
		i += copy(dAtA[i:], m.Avatar)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	if len(m.Timezone) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Timezone)))
		i += copy(dAtA[i:], m.Timezone)
	}
	if len(m.Locale) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Locale)))
		i += copy(dAtA[i:], m.Locale)
	}
	return i, nil
}

func (m *ProfilePayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfilePayload) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.UserUUID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.UserUUID)))
		i += copy(dAtA[i:], m.UserUUID)
	}
	if len(m.ScreenName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.ScreenName)))
		i += copy(dAtA[i:], m.ScreenName)
	}
	if len(m.Avatar) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Avatar)))
		i += copy(dAtA[i:], m.Avatar)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	if len(m.Timezone) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Timezone)))
		i += copy(dAtA[i:], m.Timezone)
	}
	if len(m.Locale) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(len(m.Locale)))
		i += copy(dAtA[i:], m.Locale)
	}
	if m.CreatedAt != nil {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(types.SizeOfStdTime(*m.CreatedAt)))
		n1, err := types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.UpdatedAt != nil {
		dAtA[i] = 0xaa
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(types.SizeOfStdTime(*m.UpdatedAt)))
		n2, err := types.StdTimeMarshalTo(*m.UpdatedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.ArchivedAt != nil {
		dAtA[i] = 0xb2
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(types.SizeOfStdTime(*m.ArchivedAt)))
		n3, err := types.StdTimeMarshalTo(*m.ArchivedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.DeletedAt != nil {
		dAtA[i] = 0xba
		i++
		dAtA[i] = 0x3e
		i++
		i = encodeVarintProfiles(dAtA, i, uint64(types.SizeOfStdTime(*m.DeletedAt)))
		n4, err := types.StdTimeMarshalTo(*m.DeletedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func encodeVarintProfiles(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *UpsertProfileOpts) Size() (n int) {
	var l int
	_ = l
	l = len(m.UserUUID)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.ScreenName)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Timezone)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Locale)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	return n
}

func (m *ProfilePayload) Size() (n int) {
	var l int
	_ = l
	l = len(m.UserUUID)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.ScreenName)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Timezone)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	l = len(m.Locale)
	if l > 0 {
		n += 1 + l + sovProfiles(uint64(l))
	}
	if m.CreatedAt != nil {
		l = types.SizeOfStdTime(*m.CreatedAt)
		n += 2 + l + sovProfiles(uint64(l))
	}
	if m.UpdatedAt != nil {
		l = types.SizeOfStdTime(*m.UpdatedAt)
		n += 2 + l + sovProfiles(uint64(l))
	}
	if m.ArchivedAt != nil {
		l = types.SizeOfStdTime(*m.ArchivedAt)
		n += 2 + l + sovProfiles(uint64(l))
	}
	if m.DeletedAt != nil {
		l = types.SizeOfStdTime(*m.DeletedAt)
		n += 2 + l + sovProfiles(uint64(l))
	}
	return n
}

func sovProfiles(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozProfiles(x uint64) (n int) {
	return sovProfiles(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UpsertProfileOpts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProfiles
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpsertProfileOpts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpsertProfileOpts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScreenName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScreenName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timezone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timezone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locale", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locale = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProfiles(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProfiles
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProfilePayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProfiles
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfilePayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfilePayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScreenName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScreenName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timezone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timezone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locale", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locale = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 996:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 997:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 998:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArchivedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ArchivedAt == nil {
				m.ArchivedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.ArchivedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 999:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeletedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProfiles
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeletedAt == nil {
				m.DeletedAt = new(time.Time)
			}
			if err := types.StdTimeUnmarshal(m.DeletedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProfiles(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProfiles
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProfiles(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProfiles
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProfiles
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthProfiles
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowProfiles
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipProfiles(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthProfiles = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProfiles   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("profiles.proto", fileDescriptorProfiles) }

var fileDescriptorProfiles = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0x59, 0x28, 0x25, 0x71, 0x44, 0x00, 0xab, 0x82, 0x65, 0x0f, 0xd9, 0x68, 0x4f, 0x45,
	0xa2, 0xbb, 0x52, 0x2a, 0x38, 0x94, 0x53, 0x22, 0x24, 0xc4, 0x05, 0xaa, 0x40, 0x38, 0x70, 0x89,
	0x9c, 0xdd, 0x69, 0x62, 0x69, 0x13, 0x5b, 0xb6, 0xb7, 0x52, 0x78, 0x8a, 0x3e, 0x16, 0xdc, 0xfa,
	0x04, 0x01, 0x85, 0xaf, 0x7b, 0x24, 0xee, 0xc8, 0x6b, 0x3b, 0x9b, 0xaa, 0x2a, 0x6d, 0xaf, 0x5c,
	0xa2, 0x9d, 0xf1, 0xfc, 0xfe, 0x33, 0xe3, 0xcc, 0x18, 0x35, 0xb9, 0x60, 0x47, 0x34, 0x07, 0x19,
	0x73, 0xc1, 0x14, 0xc3, 0x8f, 0x53, 0x32, 0x23, 0x62, 0x3e, 0x01, 0x92, 0xab, 0x49, 0x4c, 0x33,
	0x1e, 0xbb, 0x80, 0x60, 0x6f, 0x4c, 0xd5, 0xa4, 0x18, 0xc5, 0x29, 0x9b, 0x26, 0x63, 0x36, 0x66,
	0x49, 0x49, 0x8c, 0x8a, 0xa3, 0xd2, 0x2a, 0x8d, 0xf2, 0xcb, 0x28, 0x05, 0xe1, 0x98, 0xb1, 0x71,
	0x0e, 0x55, 0x94, 0xa2, 0x53, 0x90, 0x8a, 0x4c, 0xb9, 0x0d, 0xd8, 0xdf, 0xd0, 0x33, 0x59, 0xf7,
	0x4c, 0xda, 0x84, 0x66, 0x3c, 0x19, 0x0a, 0x9e, 0x26, 0x85, 0x04, 0x21, 0xcd, 0xaf, 0x85, 0x0e,
	0x2e, 0x84, 0xaa, 0x3c, 0x73, 0x0e, 0x32, 0x21, 0xea, 0xbd, 0xcb, 0xe7, 0xd8, 0xce, 0x55, 0xd9,
	0xa2, 0xa0, 0x99, 0x65, 0x9e, 0x5f, 0x95, 0xc9, 0xa9, 0x54, 0x6f, 0xb9, 0xb2, 0xb9, 0xa2, 0x3f,
	0x1e, 0x7a, 0x30, 0xe0, 0x12, 0x84, 0x3a, 0x34, 0xf7, 0xa7, 0xcf, 0xf0, 0x0b, 0x54, 0xd7, 0xcd,
	0x0c, 0x75, 0x02, 0xdf, 0x6b, 0x7b, 0xbb, 0xf5, 0x5e, 0x6b, 0xb9, 0x08, 0x6b, 0x03, 0x09, 0x62,
	0x30, 0x78, 0xfd, 0x72, 0xb5, 0x08, 0x9b, 0xd9, 0xe8, 0x20, 0x5a, 0x07, 0x45, 0xfd, 0x9a, 0xfe,
	0x1e, 0x14, 0x34, 0xc3, 0xcf, 0x50, 0x43, 0xa6, 0x02, 0x60, 0x36, 0x9c, 0x91, 0x29, 0xf8, 0x37,
	0x4b, 0x7c, 0x67, 0xb5, 0x08, 0xef, 0x6b, 0x64, 0xe3, 0x28, 0xea, 0x23, 0x63, 0xbd, 0x21, 0x53,
	0xc0, 0x0f, 0xd1, 0x36, 0x39, 0x26, 0x8a, 0x08, 0xff, 0x96, 0x26, 0xfa, 0xd6, 0xc2, 0x6d, 0xd4,
	0xc8, 0x40, 0xa6, 0x82, 0x72, 0x45, 0xd9, 0xcc, 0xdf, 0x2a, 0x0f, 0x37, 0x5d, 0x38, 0x40, 0x35,
	0xfd, 0x9f, 0x7d, 0x62, 0x33, 0xf0, 0x6f, 0x97, 0xc7, 0x6b, 0x5b, 0xab, 0xe6, 0x2c, 0x25, 0x39,
	0xf8, 0xdb, 0x46, 0xd5, 0x58, 0xd1, 0x97, 0x2d, 0xd4, 0xb4, 0x1d, 0x1f, 0x92, 0x79, 0xce, 0x48,
	0xf6, 0xff, 0x37, 0x8d, 0xdf, 0x21, 0x94, 0x0a, 0x20, 0x0a, 0xb2, 0x21, 0x51, 0xfe, 0x8f, 0x3b,
	0x6d, 0x6f, 0xb7, 0xd1, 0x09, 0x62, 0xb3, 0x00, 0xb1, 0x1b, 0x94, 0x78, 0x3d, 0x90, 0xbd, 0x47,
	0xab, 0x45, 0x78, 0x4f, 0x37, 0x50, 0x61, 0xd1, 0xc9, 0xd7, 0xd0, 0xeb, 0xd7, 0xad, 0xa3, 0xab,
	0xb4, 0x68, 0xc1, 0x33, 0x27, 0xfa, 0xf3, 0x1a, 0xa2, 0x15, 0x66, 0x45, 0xad, 0xa3, 0xab, 0xf0,
	0x07, 0xd4, 0x20, 0x22, 0x9d, 0xd0, 0x63, 0xa3, 0xfa, 0xeb, 0x72, 0x55, 0xdf, 0xdd, 0xf5, 0x06,
	0x67, 0x64, 0x91, 0xf3, 0x98, 0x62, 0x33, 0xc8, 0xc1, 0x16, 0xfb, 0xfb, 0x1a, 0xc5, 0x56, 0x98,
	0x2d, 0xd6, 0x3a, 0xba, 0xaa, 0x73, 0xea, 0xa1, 0x9a, 0x9d, 0x25, 0x89, 0x87, 0xe8, 0xee, 0x99,
	0x7d, 0xc2, 0x4f, 0xe3, 0x0b, 0x9f, 0xaa, 0xf8, 0xdc, 0xe6, 0x05, 0xed, 0xf3, 0xd1, 0xe6, 0x59,
	0x71, 0x53, 0x88, 0x53, 0xb4, 0xf3, 0x0a, 0x1c, 0xd3, 0x9b, 0xaf, 0xfd, 0x97, 0x92, 0xc1, 0x93,
	0x7f, 0x54, 0x72, 0x76, 0x17, 0x7a, 0xc1, 0xe7, 0x65, 0xcb, 0x3b, 0x5d, 0xb6, 0xbc, 0x6f, 0xcb,
	0x96, 0x77, 0xf2, 0xbd, 0x75, 0xe3, 0x63, 0xcd, 0x85, 0x8e, 0xb6, 0xcb, 0x6b, 0xda, 0xff, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x2b, 0xb0, 0x13, 0xf8, 0x93, 0x05, 0x00, 0x00,
}
