// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import user "github.com/canary-health/idp/internal/user"

// UserDomain is an autogenerated mock type for the UserDomain type
type UserDomain struct {
	mock.Mock
}

// IsUserValid provides a mock function with given fields: ctx, opts
func (_m *UserDomain) IsUserValid(ctx context.Context, opts *user.UpsertUserOpts) (bool, error) {
	ret := _m.Called(ctx, opts)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, *user.UpsertUserOpts) bool); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *user.UpsertUserOpts) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
